mode = "download"

[[tools]]
url = "https://github.com/FiloSottile/age/releases/download/v{{ $.Version }}/age-v{{ $.Version }}-linux-amd64.tar.gz"
version = "1.3.1"
arguments = ["age", "tar", "--version", "v{{ $.Version }}"]
