mode = "download"

[[tools]]
version = "3.0.4"
url = "https://gitlab.alpinelinux.org/api/v4/projects/5/packages/generic/v{{ $.Version }}/x86_64/apk.static"
arguments = ["apk", "binary", "--version", " {{ $.Version }},"]
