mode = "vimplugin"

[[tools]]
url = "https://github.com/vim-airline/vim-airline"

[[tools]]
url = "https://github.com/hrsh7th/nvim-cmp"

[[tools]]
url = "https://github.com/hrsh7th/cmp-nvim-lsp"

[[tools]]
url = "https://github.com/mhartington/formatter.nvim"

[[tools]]
url = "https://github.com/mfussenegger/nvim-lint"

[[tools]]
url = "https://github.com/L3MON4D3/LuaSnip"

[[tools]]
url = "https://github.com/hrsh7th/cmp-buffer"
