[language-server.gopls]
command = "gopls"
config = { "gofumpt" = true, "staticcheck" = true }

[language-server.efm]
command = "efm-langserver"

[[language]]
language-servers = [ "efm" ]
name = "bash"

[[language]]
name = "python"
language-servers = ["basedpyright", "ruff"]
